/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */

export type ArchiveFormat = typeof ArchiveFormat[keyof typeof ArchiveFormat];


export const ArchiveFormat = {
  cbz: 'cbz',
  cb7: 'cb7',
} as const;
