/**
 * Generated by orval v8.6.2 🍺
 * Do not edit manually.
 * OpenAPI spec version: 0.0.1
 */
import type { ArchiveFormat } from './archiveFormat';

export interface ExportArchiveRequest {
  format: ArchiveFormat;
}
